FROM confluentinc/cp-kafka-connect:7.6.0

# Install Debezium PostgreSQL connector
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.6.1

# Install ClickHouse Sink connector
RUN confluent-hub install --no-prompt clickhouse/clickhouse-kafka-connect:0.14.0
